# -*- coding: utf-8 -*-
"""1kml_scoreMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hspePd5N6g7p9o0Ysp41jOgYOLWgyVUE
"""

import folium
import pandas as pd
import json
import re



geo_json=km2


m=folium.Map(
    location=[37.566345,126.977893],
    tiles='Stamen Terrain'
)

folium.Choropleth(
    geo_data=geo_json,
    name='choropleth',
    data = km2,
    columns=['total'],
    key_on='feature.properties.name',
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2
).add_to(m)

from google.colab import drive
drive.mount('/content/drive')

km2 = pd.read_csv('/content/drive/My Drive/elice_miniProject/seoul_1km.csv')

km2

import json



with open('/content/drive/My Drive/elice_miniProject/geo.json', 'r') as f:

    json_data = json.load(f)

import pandas as pd

km = pd.read_csv('/content/drive/My Drive/elice_miniProject/seoul_score.csv')

km2['total'] = 0.0

km2['total'] = km['starbucks']+km['cu']+km['gs25']+km['seven11']+km['olive0']+km['mcdonalds']

km2

km2 = km.reset_index(drop=False, inplace=False)
km2

km2['total_x']=0.0
km2['total_y']=0.0
for i in range(len(km2['index'])):
  km2['total_y'][i] = (km2['bottom_left_y'][i] + km2['bottom_right_y'][i])/2
  km2['total_x'][i] = (km2['bottom_left_x'][i] + km2['top_left_x'][i])/2

km2

state_geo = 'https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'

km2['total']=km2['total']/10

for i in range(len(km2['total'])):
  if km2['total'][i]==0.0:
    km2['total'][i]=None

km2

# 색상을 붉은 색으로 해서 범죄 발생 건수를 넣자.
map = folium.Map(location=[37.5502, 126.982], zoom_start=11)

map.choropleth(
    geo_data=state_geo,
    fill_color='Blues',
    fill_opacity=0.2,
    line_opacity=1,
    color = 'gray',
  
)


for n in km2['index']:
    folium.CircleMarker([km2['total_x'][n], km2['total_y'][n]],
                        radius = km2['total'][n]*6,
                       color='#3186cc', fill_color='#3186cc').add_to(map)
map

json_data['features'][1]['properties']['name']

json_data['features'][1]['properties']['code']

len(json_data['features'])

import requests
import json

url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={0}&y={1}".format(km2['total_y'][0],km2['total_x'][0])
headers = {"Authorization": "KakaoAK 2e021e0dbc0637b7c8a74be86c202a11"}
api_test = requests.get(url,headers=headers)
url_text = json.loads(api_test.text)

url_text

url_text['documents'][0]['address_name'].split()[1]

# km2['gu']=''

# km2['code']=''

for i in range(len(km2['total'])):
  url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={0}&y={1}".format(km2['bottom_left_y'][i],km2['bottom_left_x'][i])
  headers = {"Authorization": "KakaoAK 2e021e0dbc0637b7c8a74be86c202a11"}
  api_test = requests.get(url,headers=headers)
  url_text = json.loads(api_test.text)
  km2['gu'][i]=url_text['documents'][0]['address_name'].split()[1]

for i in range(len(km2['total'])):
  for j in range(len(json_data['features'])):
    if km2['gu'][i]==json_data['features'][j]['properties']['name']:
      km2['code'][i]=json_data['features'][j]['properties']['code']

km2

# 색상을 붉은 색으로 해서 범죄 발생 건수를 넣자.
map = folium.Map(location=[37.5502, 126.982], zoom_start=11)

map.choropleth(
    geo_data=state_geo,
    fill_color='PuRd',
    fill_opacity=0.5,
    line_opacity=1,
     data = km2,
      columns = ['gu','total'],
     key_on='feature.properties.name'
)


for n in km2['index']:
    folium.CircleMarker([km2['total_x'][n], km2['total_y'][n]],
                        radius = km2['total'][n]*6,
                       color='#3186cc', fill_color='#3186cc').add_to(map)

map

for i in range(len(km2['total'])):
  if km2['total'][i]!=float:
    km2['total'][i]=0.0

km2

km2.to_csv('/content/drive/My Drive/elice_miniProject/seoul_scoreMap.csv',index=False,encoding='utf-8')

