# -*- coding: utf-8 -*-
"""add_xy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h7_Tyg3XEOtUzH8QcdbFZJeREUoOsk5e
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import json
import requests
from urllib.parse import urlparse

df = pd.read_csv('/content/drive/My Drive/elice_miniProject/starbucks_seoul.csv', encoding="cp949")

df.head()

del df['Unnamed: 0']

## y,x열 추가

df['y'] = 0
df['x'] = 0

df.loc[0][1]

d = []

for i in range(len(df['지점명'])):
  adress = df.loc[i][1]
  url = "https://dapi.kakao.com/v2/local/search/address.json?&query="+adress
  result = requests.get(urlparse(url).geturl(), headers={"authorization":"KakaoAK 2e021e0dbc0637b7c8a74be86c202a11"})
  url_text = result.json()
  try:
    ## 주소가 있는 경우 값 추가
    df['y'][i] = url_text['documents'][0]['y']
    df['x'][i] = url_text['documents'][0]['x']
  except:
    ## 주소를 구할 수  없는 경우 행 번호 수집
    d.append(i)
    print(d)

## 숫자가 큰 순서의 행 부터 삭제
## 작은 순으로 삭제하면 행의 길이가 바뀌기 때문에 귀찮아짐
d.sort(reverse=True)

for i in d:
  df = df.drop(index=i)

df = df.reset_index(drop=True, inplace=False)
df

## 매장명 마지막 점검
c = [] 
for i in range(len(df['지점명'])):
  a = df['지점명'][i].split()[0]
  if a != '스타벅스':
    c.append(i)
print(c)

df = df.drop(index=i)
df = df.reset_index(drop=True, inplace=False)
df

df.to_csv('/content/drive/My Drive/elice_miniProject/starbucks_seoul.csv',index=False,encoding='utf-8')



