# -*- coding: utf-8 -*-
"""seoul300_scoreMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d7aalt2yRewi8dmCFKiKgjWwJv5jm3P9
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
km2 = pd.read_csv('/content/drive/My Drive/elice_miniProject/seoul300_score.csv')

km2

km2['total'] = km2['starbucks']+km2['cu']+km2['gs25']+km2['seven11']+km2['olive0']+km2['mcdonalds']

km2

km2['total_x']=0.0
km2['total_y']=0.0
for i in range(len(km2['cu'])):
  km2['total_y'][i] = (km2['bottom_left_y'][i] + km2['bottom_right_y'][i])/2
  km2['total_x'][i] = (km2['bottom_left_x'][i] + km2['top_left_x'][i])/2

km2

state_geo = 'https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'

km2['total']=km2['total']/10

for i in range(len(km2['total'])):
  if km2['total'][i]==0.0:
    km2['total'][i]=None

km2

import folium
# 색상을 붉은 색으로 해서 범죄 발생 건수를 넣자.
map = folium.Map(location=[37.5502, 126.982], zoom_start=11)

map.choropleth(
    geo_data=state_geo,
    fill_color='Blues',
    fill_opacity=0.2,
    line_opacity=1,
    color = 'gray',
  
)


for n in range(len(km2['cu'])):
    folium.CircleMarker([km2['total_y'][n], km2['total_x'][n]],
                        radius = km2['total'][n]*10,
                       color='#3186cc', fill_color='#3186cc').add_to(map)
map

json_data['features'][1]['properties']['name']

json_data['features'][1]['properties']['code']

len(json_data['features'])

import requests
import json

url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={0}&y={1}".format(km2['total_y'][0],km2['total_x'][0])
headers = {"Authorization": "KakaoAK 2e021e0dbc0637b7c8a74be86c202a11"}
api_test = requests.get(url,headers=headers)
url_text = json.loads(api_test.text)

url_text

url_text['documents'][0]['address_name'].split()[1]

# km2['gu']=''

# km2['code']=''

for i in range(len(km2['total'])):
  url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={0}&y={1}".format(km2['bottom_left_y'][i],km2['bottom_left_x'][i])
  headers = {"Authorization": "KakaoAK 2e021e0dbc0637b7c8a74be86c202a11"}
  api_test = requests.get(url,headers=headers)
  url_text = json.loads(api_test.text)
  km2['gu'][i]=url_text['documents'][0]['address_name'].split()[1]

for i in range(len(km2['total'])):
  for j in range(len(json_data['features'])):
    if km2['gu'][i]==json_data['features'][j]['properties']['name']:
      km2['code'][i]=json_data['features'][j]['properties']['code']

km2

# 색상을 붉은 색으로 해서 범죄 발생 건수를 넣자.
map = folium.Map(location=[37.5502, 126.982], zoom_start=11)

map.choropleth(
    geo_data=state_geo,
    fill_color='PuRd',
    fill_opacity=0.5,
    line_opacity=1,
     data = km2,
      columns = ['gu','total'],
     key_on='feature.properties.name'
)


for n in km2['index']:
    folium.CircleMarker([km2['total_x'][n], km2['total_y'][n]],
                        radius = km2['total'][n]*6,
                       color='#3186cc', fill_color='#3186cc').add_to(map)

map

for i in range(len(km2['total'])):
  if km2['total'][i]!=float:
    km2['total'][i]=0.0

km2

km2.to_csv('/content/drive/My Drive/elice_miniProject/seoul_scoreMap.csv',index=False,encoding='utf-8')

