# -*- coding: utf-8 -*-
"""seoul500_scoreMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWvvcEOC_pINXQT0rkUbsth8A0uCZLsB
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
km2 = pd.read_csv('/content/drive/My Drive/elice_miniProject/seoul500_score.csv')

km2

km2['total'] = 0.0

km2['total'] = km2['starbucks']+km2['cu']+km2['gs25']+km2['seven11']+km2['olive0']+km2['mcdonalds']

km2



km2 = km.reset_index(drop=False, inplace=False)
km2

km2['total_x']=0.0
km2['total_y']=0.0
for i in range(len(km2['cu'])):
  km2['total_y'][i] = (km2['bottom_left_y'][i] + km2['bottom_right_y'][i])/2
  km2['total_x'][i] = (km2['bottom_left_x'][i] + km2['top_left_x'][i])/2

km2

state_geo = 'https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'

km2['total']=km2['total']/10

for i in range(len(km2['total'])):
  if km2['total'][i]==0.0:
    km2['total'][i]=None

km2

import folium
# 색상을 붉은 색으로 해서 범죄 발생 건수를 넣자.
map = folium.Map(location=[37.5502, 126.982], zoom_start=11)

map.choropleth(
    geo_data=state_geo,
    fill_color='Blues',
    fill_opacity=0.2,
    line_opacity=1,
    color = 'gray'
  
)


for n in range(len(km2['cu'])):
    folium.CircleMarker([km2['total_y'][n], km2['total_x'][n]],
                        radius = km2['total'][n]*8,
                       color='#3186cc', fill_color='#3186cc').add_to(map)
map

km2.to_csv('/content/drive/My Drive/elice_miniProject/seoul500_scoreMap.csv',index=False,encoding='utf-8')

