# -*- coding: utf-8 -*-
"""seoul_score500.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MCz3lUV-3Za09-g_HiOiMxpiZ28km-ce
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

km = pd.read_csv('/content/drive/My Drive/elice_miniProject/seoul_500m.csv')

km['starbucks']=0
km['seven11']=0
km['gs25']=0
km['olive0']=0
km['mcdonalds']=0
km['cu']=0
km

## 매장 좌표가 1구획의 좌하단 and 우상단 좌표 내에 포함되어 있으면 +1 
def score(df,km,a):
  for i in range(len(km['bottom_left_x'])):
    for j in range(len(df['x'])):
      if km['bottom_left_x'][i] <= df['x'][j] and km['bottom_left_y'][i] <= df['y'][j] and km['top_right_x'][i] > df['x'][j] and km['top_right_y'][i] > df['y'][j]:
        a[i] = a[i] + 1

## 범위 내에 들어온 매장 수 합계
  n=0
  for c in range(len(a)):
    if a[c] > 0:
      n = n + a[c]
  print('total:',n)

  return km

store = ['cu_seoul','gs25_seoul','seven11_seoul','mcdonalds_seoul','olive0_seoul','starbucks_seoul']
for i in range(len(store)): 
  df = pd.read_csv('/content/drive/My Drive/elice_miniProject/'+store[i]+'.csv')
  df.columns = ['지점명','지점주소','y','x']
  df = df.sort_values('y',ascending=True)
  df = df.reset_index(drop=True, inplace=False)
  df

  score(df,km,km[store[i].split('_')[0]])

km

km.to_csv('/content/drive/My Drive/elice_miniProject/seoul500_score.csv',index=False,encoding='utf-8')

[km['bottom_left_y'][0],km['bottom_left_x'][0]]

